name: Download artifact
run-name: ${{ github.actor }} is downloading artifacts
on: [push]
jobs: 
  download artifact:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Download artifact sample"
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with: 
          name: output-log-file